### ISSUE TITLE
about live demos

### ISSUE THREAD

**Issue by cy-xu** [mitvis/shared-interest#2]
Hi Angie, 

Thank you for this great work. I have a quick question - do you have plans to open-source the three live demos? 

Best,
CY

**Comment by aboggust** [comment]
Hi CY, 

Thanks for reaching out! 

I didn't currently have plans to open source the demos. They are scoped demo interfaces, so they weren't designed to extend to different datasets/modalities/tasks.

But if they would be valuable to you, I could make them public. Let me know!

Best,
Angie

**Comment by cy-xu** [comment]
Hi Angie, 

Thank you for your response! I was looking into front-end and back-end solutions to build similar interfaces a while ago. I got some inspiration from other works but I will reopen the ticket if I need them. Thanks for your kind offer!

Closing the issue for now.

Best,
CY
